In [1]:
import cv2
import numpy as np
import os 


def save_ckeckerboard_image(filename,squre_size_cm):
    rows,cols=8,8
    pixel_per_cm = 100
    square_size_px = int(squre_size_cm * pixel_per_cm)
    pattern =np.zeros((rows*square_size_px,cols*square_size_px),dtype=np.uint8)
    
    for i in range (0,rows,2):
        for j in range (0,cols,2):
            pattern[i*square_size_px:(i+1)*square_size_px,j*square_size_px:(j+1)*square_size_px]=255
        
    for i in range (1,rows,2):
        for j in range (1,cols,2):
            pattern[i*square_size_px:(i+1)*square_size_px,j*square_size_px:(j+1)*square_size_px]=255

    cv2.imwrite(filename,pattern)
    print(f"checkerboard image saved as {filename}")


save_ckeckerboard_image("checkerboard.png", squre_size_cm= 2.5 )

checkerboard image saved as checkerboard.png


In [6]:
chess_board_dim =(7,7) #number of corners

n=0 
image_dir="images"

check_dir = os.path.isdir(image_dir)
if not check_dir:
    os.makedirs(image_dir)
    print(f"{image_dir}Directory is created ")
else:
    print(f"{image_dir}Directory already exists ")
    

criteria = (cv2.TermCriteria_EPS + cv2.TermCriteria_MAX_ITER, 30, 0.001)

def detect_checkerborad(image,grayImage,criteria,boardDimesions):
    ret , corners = cv2.findChessboardCorners(grayImage,boardDimesions)
    if ret == True:
        corner1=cv2.cornerSubPix(grayImage,corners,(3,3),(-1,-1),criteria)
        image = cv2.drawChessboardCorners(image,boardDimesions,corner1,ret)
    return image , ret


cap = cv2.VideoCapture(0)
while True:
    _,frame = cap.read()
    copyFrame = frame.copy()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    image ,board_detected = detect_checkerborad(frame,gray,criteria,chess_board_dim)
    cv2.putText(frame,f"saved_image:{n}",(30,40),cv2.FONT_HERSHEY_PLAIN,1.4,(0,255,0),2)
    
    cv2.imshow("frame",frame)
    cv2.imshow("copyframe",copyFrame)
    
    key = cv2.waitKey(1)
    
    if key ==ord("q"):
        break
    if key == ord("s") and board_detected == True:
        cv2.imwrite(f"{image_dir}/checkerboard_{n}.png",copyFrame)
        print(f"saved image number {n}")
        n+=1
cap.release()
cv2.destroyAllWindows()
print(f"Total images saved: {n}")
              


imagesDirectory is created 
Total images saved: 0


In [21]:
squared_size = 25

calib_data_path  = "calib_data"
check_dir = os.path.isdir(calib_data_path)
if not check_dir:
    os.makedirs(calib_data_path)
    print(f"{calib_data_path}Directory is created ")
else:
    print(f"{calib_data_path}Directory already exists ")
    
obj_3d = np.zeros((chess_board_dim[0]*chess_board_dim[1],3),np.float32)
obj_3d[:,:2]=np.mgrid[0:chess_board_dim[0],0:chess_board_dim[1]].T.reshape(-1,2)*squared_size
print(obj_3d)


obj_points_3d = []
img_points_2d = []

image_dir = r"C:\Users\youssef\Desktop\CALIBRATIONS\Calibartion_Camera_with_checkerboard\images"
files = os.listdir(image_dir)

for file in files : 
    print (file)
    imagepath = os.path.join(image_dir,file)
    image = cv2.imread(imagepath)
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    ret , corners = cv2.findChessboardCorners(gray,chess_board_dim,None)
    if ret ==True :
        obj_points_3d.append(obj_3d)
        corner2= cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        img_points_2d.append(corner2)
        img = cv2.drawChessboardCorners(image,chess_board_dim,corner2,ret)

cv2.destroyAllWindows()
ret,mtx,dist,rvecs,tvecs = cv2.calibrateCamera(obj_points_3d,img_points_2d,gray.shape[::-1],None,None)
print ("calibrated")

print("duming the data into one files using numpy ")
np.savez(
    f"{calib_data_path}/MultiMatrix",
    camMatrix=mtx,
    distCoef=dist,
    rVector=rvecs,
    tVector=tvecs,
)

calib_dataDirectory already exists 
[[  0.   0.   0.]
 [ 25.   0.   0.]
 [ 50.   0.   0.]
 [ 75.   0.   0.]
 [100.   0.   0.]
 [125.   0.   0.]
 [150.   0.   0.]
 [  0.  25.   0.]
 [ 25.  25.   0.]
 [ 50.  25.   0.]
 [ 75.  25.   0.]
 [100.  25.   0.]
 [125.  25.   0.]
 [150.  25.   0.]
 [  0.  50.   0.]
 [ 25.  50.   0.]
 [ 50.  50.   0.]
 [ 75.  50.   0.]
 [100.  50.   0.]
 [125.  50.   0.]
 [150.  50.   0.]
 [  0.  75.   0.]
 [ 25.  75.   0.]
 [ 50.  75.   0.]
 [ 75.  75.   0.]
 [100.  75.   0.]
 [125.  75.   0.]
 [150.  75.   0.]
 [  0. 100.   0.]
 [ 25. 100.   0.]
 [ 50. 100.   0.]
 [ 75. 100.   0.]
 [100. 100.   0.]
 [125. 100.   0.]
 [150. 100.   0.]
 [  0. 125.   0.]
 [ 25. 125.   0.]
 [ 50. 125.   0.]
 [ 75. 125.   0.]
 [100. 125.   0.]
 [125. 125.   0.]
 [150. 125.   0.]
 [  0. 150.   0.]
 [ 25. 150.   0.]
 [ 50. 150.   0.]
 [ 75. 150.   0.]
 [100. 150.   0.]
 [125. 150.   0.]
 [150. 150.   0.]]
checkerboard_0.png
checkerboard_1.png
checkerboard_10.png
checkerboard_11.png
che

In [22]:
print("loading data stored using numpy savez function\n \n \n")

data = np.load(f"{calib_data_path}/MultiMatrix.npz")

camMatrix = data["camMatrix"]
distCof = data["distCoef"]
rVector = data["rVector"]
tVector = data["tVector"]

print("loaded calibration data successfully")

loading data stored using numpy savez function
 
 

loaded calibration data successfully
